   version: '3.8'

   services:
     backend:
       build:
         context: ./backend
         dockerfile: Dockerfile
       networks:
         - my_network  
       volumes:
         - data-volume:/app/data  
       restart: always  

     frontend:
       build:
         context: ./frontend
         dockerfile: Dockerfile
       depends_on:
         - backend  
       networks:
         - my_network  
       restart: always  

   volumes:
     data-volume: 

   networks:
     my_network:
       driver: bridge  