version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - my_network  
    volumes:
      - data-volume:/app/data  
    restart: always
    ports:
      - "8080:8080"  # Пробрасываем порт backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend  
    networks:
      - my_network  
    restart: always
    ports:
      - "80:80"  # Пробрасываем порт frontend

volumes:
  data-volume: 

networks:
  my_network:
    driver: bridge